routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Input;
use App\Employee;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::get('/admin', 'AdminController@admin')    
    ->middleware(['is_admin'])    
    ->name('admin');

Route::resource('employee','EmployeeController');
Route::resource('department','DepartmentController');
Route::resource('role','RoleController');
// Route::resource('payroll','PayrollController');
Route::get('/employee/payroll/{id}', 'PayrollController@payrollIndex')->name('payrolls.show');
Route::get('/payrolls/create/{id}', 'PayrollController@create')->name('payrolls.create');
Route::post('/payrolls/{id}', 'PayrollController@store')->name('payrolls.store');
Route::get('/employee/payroll/{id}/edit', 'PayrollController@edit')->name('payrolls.edit');
Route::patch('/payrolls/update/{id}', 'PayrollController@update')->name('payrolls.update');

Route::delete('/payrolls/delete/{id}', 'PayrollController@destroy')->name('payrolls.destroy');



Route::any('/search',function(){
    $q = Input::get ( 'q' );
    $employee = Employee::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->get();
    if(count($employee) > 0)
        return view('employee.index')->withDetails($employee)->withQuery ( $q );
    else return view ('employee.index')->withMessage('No Details found. Try to search again !');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Employee extends Model
{
    // use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    use SoftDeletes;

    protected $dates=['deleted_at'];

    protected $fillable = [
        'name', 'slug','address','email','contactnumber','gender','role_id','full_time',
    ];
    public $with = ['role','payrolls'];

    public function role(){
        return $this->belongsTo('App\Role');

    }

    public function payrolls(){
        return $this->hasMany('App\Payroll');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Employee;
use App\Role;
use App\Department;
use App\Payroll;
use Session;
use paginate;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $emp = Employee::all();
        return view('employee.index', ['details'=>Employee::paginate(50)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $roles=Role::all();
        if($roles->count()==0){
            Session::flash('Success','you must have atleast 1 role created before attempting to create am employee');
            return redirect()->back;
        }
        return view('employee.create')->with('roles',$roles);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required|max:255',
            'address'=>'required',
            'email'=>'required|email',
            'contactnumber'=>'required',
            'gender'=>'required',
            'role_id'=>'required',
            'full_time'=>'required|bool'


        ]);
        
        $employee = Employee::create([
            'name' => $request->name,
            'slug' => str_slug($request->name),
            'email' => $request->email,
            'address' => $request->address,
            'contactnumber' => $request->contactnumber,
            'gender' => $request->gender,
            'role_id' => $request->role_id,
            'full_time' => $request->full_time,

        ]);

        $payroll = new Payroll;
        $payroll->employee_id = $employee->id;
        $payroll->save();
        $employee->save();

        $request->session()->flash('status','New Employee created');
        return redirect()->route('employee.index');

        
    }
    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('employee.show',['employee'=>Employee::findOrFail($id)]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('employee.edit',['employee'=>Employee::find($id),
        'roles'=>Role::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $employee=Employee::findOrFail($id);
        $this->validate($request,[
            'name'=>'required',
            'address'=>'required',
            'email'=>'required',
            'contactnumber'=>'required',
            'gender'=>'required',
            'role_id'=>'required',
            'full_time'=>'required',

        ]);

        $employee->name = $request->name;
		$employee->slug = str_slug($request->name);
		$employee->address = $request->address;
        $employee->email = $request->email;
        $employee->contactnumber = $request->contactnumber;
        $employee->gender = $request->gender;
		$employee->full_time = $request->full_time;
		$employee->role_id  = $request->role_id;		
		$employee->save();
		
		$request->session()->flash('status', 'New Employee created');
		return redirect()->route('employee.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->delete();

        Session::flash('success','Employee deleted');
        return redirect()->route('employee.index');

    }
}

resources/views/employee/create.blade.php
@extends('layouts.master')

@section('content')  

<div class="container">
<form method="post" action="{{route('employee.store')}}" name="form1" enctype="multipart/form-data" ><br/>
    {{csrf_field()}}
    <div class="float-left"><h4>Add Employees</h4></div>
    <div class="float-right"><a href="{{route('employee.index')}}" class="btn btn-success">Back</a></div> <br>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group col-md-12">
                <label>Employee Name</label>
                <input type="name" class="form-control" name="name" placeholder="Name">
                {{-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> --}}
            </div>
            <div class="form-group col-md-12 ">
                <label>Address</label>
                <input type="text" class="form-control" name="address" placeholder="Address">
            </div>
            <div class="form-group col-md-12">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" placeholder="Email">
                </div>
            <div class="form-group col-md-12">
                <label>Contact Number</label>
                <input type="integer" class="form-control" name="contactnumber" placeholder="Phone Number">
            </div>
        </div>
        <div class="col-md-6">
        <div class="form-group col-md-12">
        <label>Gender</label>
        <select class="form-control" name="gender">
            <option>Male</option>
            <option>Female</option>
            <option>Others</option>
        </select>
        </div>

        <div class="form-group col-md-12">
			<label for="role">Select a Role</label>
			<select name="role_id"  cols="5" rows="5" class="form-control">
				@foreach($roles as $role)
					<option value="{{ $role->id}}">{{ $role->name }}</option>
				@endforeach
			</select>
        </div>
        
        <div class="form-group col-md-12">
			<label for="full_time">Position:</label>
			<select name="full_time" id="full_time" class="form-control">
				<option value="1">Full-Time</option>
				{{-- <option value="0">Part-Time</option>					 --}}
			</select>
		</div>

       
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        
    </div>
</form>
</div>
    
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.master')

@section('content')  

<div class="container">
<form method="post" action="{{route('employee.update', $employee->id)}}" name="form1" enctype="multipart/form-data" ><br/>
    @method('PATCH')
    {{csrf_field()}}
    <div class="float-left"><h4>Add Employees</h4></div>
    <div class="float-right"><a href="{{route('employee.index')}}" class="btn btn-success">Back</a></div> <br>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label>Employee Name</label>
                <input type="name" class="form-control" name="name" value="{{ $employee->name }}">
                {{-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> --}}
            </div>
            <div class="form-group">
                <label>Address</label>
            <input type="text" class="form-control" name="address" value="{{ $employee->address }}">
            </div>
            <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control" name="email" value="{{ $employee->email }}">
                </div>
            <div class="form-group">
                <label>Contact Number</label>
                <input type="integer" class="form-control" name="contactnumber" value="{{ $employee->contactnumber }}">
            </div>
        </div>
        <div class="col-md-6">
            <label>Gender</label>
            <select class="form-control" name="gender" value="{{ $employee->gender }}">
                <option>Male</option>
                <option>Female</option>
                <option>Others</option>
            </select>

            <div class="form-group">
                <label for="role">Select a Role</label>
                <select name="role_id"  cols="5" rows="5" class="form-control">
                    @foreach($roles as $role)
                        <option value="{{ $role->id}}">{{ $role->name }}</option>
                    @endforeach
                </select>
            </div>
            
            <div class="form-group">
                <label for="full_time">Position:</label>
                <select name="full_time" id="full_time" class="form-control">
                    <option value="1">Full-Time</option>
                    <option value="0">Part-Time</option>					
                </select>
            </div>

            
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    
        
</form>
</div>
</div>
    
@endsection

resources/views/employee/index.blade.php
@extends('layouts.master')

@section('content')

<div class="container">
    <hr>	
    <h3 class="text-center">Employees Details</h3>	
    <hr> 
    <div class="float-left">
        <a href="{{route('employee.create')}}" class="btn btn-success">Create</a>
    </div>
    
    <div class="float-right">
        <a href="{{route('employee.index')}}" class="btn btn-success">Back</a>
    </div><br><br>


    {{-- search bar--}}
    <form action="/search" method="post" role="search">
        {{ csrf_field() }}
        <div class="input-group">
            <input type="text" class="form-control" name="q"
                placeholder="Search users"> <span class="input-group-btn">
                <button type="submit" class="btn btn-primary">
                    <span>Search</span>
                </button>
            </span>
        </div> 
    </form>
    @if(isset($details))
     <table class="table table-hover">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Address</th>
            <th>Email</th>
            <th>Contact</th>
            <th>Gender</th>
            <th>Role</th>
            <th>Action</th>
        </tr>
       
        @if($details->count()>0)
        @foreach ( $details as $employee)
        <tr>
            <td>{{ $employee->id }}</td>
           
            <td>{{ $employee->name }}</td>
            <td>{{ $employee->address }}</td>
            <td>{{ $employee->email }}</td>
            <td>{{ $employee->contactnumber }}</td>
            <td>{{ $employee->gender }}</td>
            <td>{{ $employee->role->name }}</td>
            <td>
                <form action="{{ route('employee.destroy',$employee->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('employee.show',$employee->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('employee.edit',$employee->id) }}">Edit</a>
                    <a href="{{ route('payrolls.show', ['id' => $employee->id]) }}" class="btn btn-info">Payroll</a>

                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        
        @endforeach
        @else
        <tr>
            <th colspan="5" class="text-center">Empty</th>
        </tr>
        @endif
    </table>
    {{-- <div class="text-center">{{ $details->links() }}</div> --}}
</div>
@endif
@endsection

resources/views/employee/show.blade.php
@extends('layouts.master')


@section('content')

<div class="container">
	<hr>
    <div class="float-left"><h4>Employee: {{ $employee->name }}</h4></div>
    <div class="float-right">
        <a href="{{route('employee.index')}}" class="btn btn-success">Back</a>
    </div> <br>
    <hr/>
       
	
	
	@auth
		<a href="{{ route('employee.edit',['id'=>$employee->id]) }}" class="btn btn-primary">Edit</a>	
		
	@endauth
	
	<br>
	<br>
	
	<table class="table table-hover" >
        <tr>
            <th>Emp ID:</th>
            <td>{{ $employee->id }}</td>		
        </tr>
		<tr>
			<th>Name:</th>
			<td>{{ $employee->name }}</td>		
		</tr>
		<tr>
			<th>Email</th>
			<td>{{ $employee->email }}</td>
		</tr>		
		<tr>
			<th>Department</th>
			<td>{{ $employee->role->department->name }}</td>
		</tr>										
		<tr>
			<th>Role</th>
			<td>{{ $employee->role->name }}</td>
		</tr>	
		<tr>
			<th> Basic Salary</th>
			<td> Rs. {{ $employee->role->salary }}</td>			
		</tr>			
		<tr>
			<th>Address</th>
			<td>{{ $employee->address }}</td>			
		</tr>
		<tr>
			<th>Number</th>
			<td>{{ $employee->contactnumber }}</td>			
		</tr>
		<tr>
			<th>Gender</th>
			<td>{{ $employee->gender }}</td>			
		</tr>
				
    </table>
</div>		
@endsection