routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Input;
use App\Employee;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::get('/admin', 'AdminController@admin')    
    ->middleware(['is_admin'])    
    ->name('admin');

Route::resource('employee','EmployeeController');
Route::resource('department','DepartmentController');
Route::resource('role','RoleController');
// Route::resource('payroll','PayrollController');
Route::get('/employee/payroll/{id}', 'PayrollController@payrollIndex')->name('payrolls.show');
Route::get('/payrolls/create/{id}', 'PayrollController@create')->name('payrolls.create');
Route::post('/payrolls/{id}', 'PayrollController@store')->name('payrolls.store');
Route::get('/employee/payroll/{id}/edit', 'PayrollController@edit')->name('payrolls.edit');
Route::patch('/payrolls/update/{id}', 'PayrollController@update')->name('payrolls.update');

Route::delete('/payrolls/delete/{id}', 'PayrollController@destroy')->name('payrolls.destroy');



Route::any('/search',function(){
    $q = Input::get ( 'q' );
    $employee = Employee::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->get();
    if(count($employee) > 0)
        return view('employee.index')->withDetails($employee)->withQuery ( $q );
    else return view ('employee.index')->withMessage('No Details found. Try to search again !');
});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable=['name','slug','salary','department_id'];
	
	public $with = ['department'];
	
	public function department(){
		return $this->belongsTo('App\Department');
	}
	
	public function employees(){
		return $this->hasMany('App\Employee');
	}
	
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Role;
use App\Department;
use App\Employee;
use Session;
use Illuminate\Http\Request;


class RoleController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      return view('role.index',['roles'=>Role::paginate(5)]);  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        if($departments->count() == 0)
        {
            Session:flash('info','You must have atleast 1 department created before attempting to create a role');
            return redirect()->back();
        }
        return view('role.create')->with('departments',$departments);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' =>'required|max:50',
            'salary' =>'required|required',
            'department_id' =>'required'
        ]);
        
        Role::create([
            'name' => $request->name,
            'salary' => $request->salary,
            'department_id' => $request->department_id,
            'slug' => str_slug($request->name),
            

        ]);

        Session::flash('success','new role created');
        return redirect()->route('role.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        return view('role.show',['role'=>Role::where('slug',$slug)->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('role.edit',['role'=>Role::find($id),
        'departments'=>Department::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $role = Role::find($id);
		
		$this->validate($request,[
			'name' =>'required|max:50',
			'salary' => 'nullable|required',
			'department_id' => 'required'
		]);
		
		$role->name = $request->name;
		$role->salary = $request->salary;
		$role->department_id = $request->department_id;
		$role->slug = str_slug($request->name);
	
		
		Session::flash('success', 'role updated!');
		return redirect()->route('role.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        foreach($role->employees as $employee)
        {
            $emloyee->forceDelete();
        }

        $role->delete();
        
        Session::flash('success','role deleted');
        return redirect()->route('role.index');
    }
}

resources/views/role/create.blade.php
@extends('layouts.master')

@section('content')  

<div class="container">
<form method="post" action="{{route('role.store')}}" name="form1" enctype="multipart/form-data" ><br/>
    {{csrf_field()}}
    <div class="float-left"><h4>Roles</h4></div>
    <div class="float-right"><a href="{{route('role.index')}}" class="btn btn-success">Back</a></div> <br>
    <hr/>
    <div class="form-group">
        <label> Name</label>
        <input type="name" class="form-control" name="name" placeholder="Name">
        {{-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> --}}
    </div>

    <div class="form-group">
        <label for="salary">Salary</label>
        <input type="number" name="salary" class="form-control" placeholder="In RS">
    </div>
    
    <div class="form-group">
        <label for="department">Select a department</label>
        <select name="department_id"  cols="5" rows="5" class="form-control">
            @foreach($departments as $department)
                <option value="{{ $department->id}}">{{ $department->name }}</option>
            @endforeach
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
    
@endsection

resources/views/role/edit.blade.php
@extends('layouts.master')


@section('content')
<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			Edit Role : {{$role->name}}
       </div>
	   
	   <div class="panel-body">
			<form method="post" action ="{{ route('role.update', ['id'=>$role->id]) }}"  enctype="multipart/form-data">
				@method('PATCH')
				{{ csrf_field()}}
				
				<div class="form-group">
					<label for="name">Name</label>
					<input type="text" name="name" value="{{$role->name}}" class="form-control">
				</div>
				
				<div class="form-group">
					<label for="salary">Salary</label>
					<input type="number" name="salary" value="{{$role->salary}}" class="form-control">
				</div>
				
				<div class="form-group">
					<label for="department">Select a department</label>
					<select name="department_id" id="department"  cols="5" rows="5" class="form-control">
						@foreach($departments as $department)
							<option value="{{ $department->id }}"
								@if($role->department->id == $department->id)
									selected							
								@endif
							   >{{ $department->name }}
							</option>
						@endforeach
					</select>
				</div>
				
				<div class="form-group">
					<div class="text-center">
						<button class ="btn btn-success" type="submit">Update</button>
					</div>
				</div>
			</form>	
	    </div>
	</div>
</div>

    
@endsection

resources/views/role/index.blade.php
@extends('layouts.master')


@section('content')

<div class="container">
    <hr>	
    <h3 class="text-center">Roles Info</h3>	
    <hr> 
    <div class="float-left">
    <a href="{{route('role.create')}}" class="btn btn-success">Create</a>
    </div><br><br>
    <hr>		
	<table class= "table table-hover">
		<thead>		
			<th>Name</th>
			<th>Department</th>
			<th>Salary</th>
			<th>Action</th>
		</thead>	
			
		<tbody>
			@if($roles->count()> 0)
				@foreach($roles as $role)
					<tr>						
						<td><a href="{{ route('role.show', ['slug' => $role->slug]) }}" >{{ $role->name}}</a></td>						
						
						<td>{{ $role->department->name }}</td>
                        <td> Rs. {{ $role->salary }}</td>
                        
                        
							
						<td>
							<form action="{{ route('role.destroy', ['id' => $role->id]) }}" method="POST">
								{{csrf_field() }}
                                {{method_field('DELETE')}}
                                <a href="{{ route('role.show', ['slug' => $role->slug]) }}" class="btn btn-info" >Show</a>
                                <a href="{{ route('role.edit', ['id' => $role->id]) }}" class="btn btn-primary">Edit</a>
					            <button class="btn btn-danger">Delete</button>
							</form>
						</td>
					</tr>
				@endforeach
			@else
				<tr> 
					<th colspan="5" class="text-center">Empty</th>
				</tr>
			@endif
		</tbody>
	</table>
</div>
@endsection

resources/views/role/show.blade.php
@extends('layouts.master')


@section('content')
<br>
<div class="container">
	<hr>
	<h3 class="page-header">Role: {{ $role->name }}</h3>
	<h4> Base Salary: Rs. {{ $role->salary }}</h4>
	<a href="{{route('role.index')}}" class="btn btn-success">Back</a>
	<hr>
	<br>
	<table class= "table table-hover">
		<thead>
			<th>Employee</th>
			<th>Email</th>
			<th>Full-Time</th>
			<th>Department</th>
		</thead>
		
		<tbody>
			@if($role->employees->count() > 0)
				@foreach($role->employees as $employee)
					<tr>
						<td>{{ $employee->name }}</td>
						<td>{{ $employee->email }}</td>
						<td>@if($employee->full_time)
								<p> Yes</p>
							@else
								<p>Part-Time</p>
							@endif
						</td>
						<td>{{ $role->department->name }}</td>
					</tr>
				@endforeach
			@else
				<tr> 
					<th colspan="5" class="text-center">No Employee assigned to this role yet</th>
				</tr>
			@endif		
		</tbody>	
	</table>
</div>	
@endsection