routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Support\Facades\Input;
use App\Employee;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/dashboard', 'HomeController@index')->name('dashboard');

Route::get('/admin', 'AdminController@admin')    
    ->middleware(['is_admin'])    
    ->name('admin');

Route::resource('employee','EmployeeController');
Route::resource('department','DepartmentController');
Route::resource('role','RoleController');
// Route::resource('payroll','PayrollController');
Route::get('/employee/payroll/{id}', 'PayrollController@payrollIndex')->name('payrolls.show');
Route::get('/payrolls/create/{id}', 'PayrollController@create')->name('payrolls.create');
Route::post('/payrolls/{id}', 'PayrollController@store')->name('payrolls.store');
Route::get('/employee/payroll/{id}/edit', 'PayrollController@edit')->name('payrolls.edit');
Route::patch('/payrolls/update/{id}', 'PayrollController@update')->name('payrolls.update');

Route::delete('/payrolls/delete/{id}', 'PayrollController@destroy')->name('payrolls.destroy');



Route::any('/search',function(){
    $q = Input::get ( 'q' );
    $employee = Employee::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->get();
    if(count($employee) > 0)
        return view('employee.index')->withDetails($employee)->withQuery ( $q );
    else return view ('employee.index')->withMessage('No Details found. Try to search again !');
});

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $fillable=['name','slug'];

    public function roles(){
        return $this->hasMany('App\Role');
    }
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Department;
use Session;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        return view('department.index', ['departments'=>Department::paginate(5)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required'
        ]);

        $department = new Department;
        $department->name = $request->name;
        $department->slug = str_slug($request->name);
        $department->save();

        // Session::flash('success','department created');
        return redirect()->route('department.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        return view('department.show',['department'=>Department::where('slug',$slug)->first()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('department.edit',['department'=>Department::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $department = Department::findOrFail($id);
		
        $this->validate($request,[
			'name' => 'required'
		]);
		
		$department->name = $request->name;
		$department->slug = str_slug($request->name);
		$department->save();
		
		// Session::flash('success', 'department updated');
		return redirect()->route('department.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $department=Department::find($id);
		
		foreach($department->roles as $role){
			$role->delete();			
		}
		
		$department->delete();
		
		Session::flash('success', 'department deleted');
		return redirect()->route('department.index');
    }
}

resources/views/department/create.blade.php
@extends('layouts.master')

@section('content')  

<div class="container">
<form method="post" action="{{route('department.store')}}" name="form1" enctype="multipart/form-data" ><br/>
    {{csrf_field()}}
    <div class="float-left"><h4>Add Departments</h4></div>
    <div class="float-right"><a href="{{route('department.index')}}" class="btn btn-success">Back</a></div> <br>
    <hr/>
    <div class="form-group">
        <label>Department Name</label>
        <input type="name" class="form-control" name="name" placeholder="Name">
        {{-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> --}}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    
    
        
</form>
</div>
    
@endsection

resources/views/department/edit.blade.php
@extends('layouts.master')

@section('content')  

<div class="container">
<form method="post" action="{{route('department.update', $department->id)}}" name="form1" enctype="multipart/form-data" ><br/>
    @method('PATCH')
    {{csrf_field()}}
    <div class="float-left"><h4>Edit Department</h4></div>
    <div class="float-right"><a href="{{route('department.index')}}" class="btn btn-success">Back</a></div> <br>
    <hr/>
    <div class="form-group">
        <label>Department Name</label>
        <input type="name" class="form-control" name="name" value="{{ $department->name }}">
        {{-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> --}}
    </div>
    <button type="submit" class="btn btn-primary">Update</button>

    
        
</form>
</div>
    
@endsection

resources/views/department/index.blade.php
@extends('layouts.master')


@section('content')
<div class="container">
   <hr>	
	<h3 class="text-center">Departments</h3>	
	<a href="{{ route('department.create') }}" class="btn btn-success">Create</a>
	<hr>
	<table class= "table table-hover">
		<thead>
            <th>Department name</th>
            <th>Action</th>			
										
		</thead>		
		<tbody>
			@if($departments->count() > 0)
				@foreach($departments as $department)
					<tr>
						<td>
							<a href="{{ route('department.show', ['slug' => $department->slug ]) }}">{{ $department->name }}</a>
						</td>
					
						<td>
							<form action="{{ route('department.destroy', ['id' => $department->id ]) }}" method="POST">
								{{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <a href="{{ route('department.show', ['slug' => $department->slug ]) }}" class="btn btn-info">Show</a>
                                <a href="{{ route('department.edit', ['id' => $department->id ]) }}" class="btn btn-primary">Edit</a>
                                <button class="btn btn-xs btn-danger">Delete</button>
							</form>
						</td>
					</tr>
				@endforeach
			@else
				<tr> 
					<th colspan="5" class="text-center">No Departments yet</th>
				</tr>
			@endif		
		</tbody>	
	</table>
</div>		
@endsection

resources/views/department/show.blade.php
@extends('layouts.master')


@section('content')
<br>

<div class="container">
    <hr>
		<h3 class="page-header">Department: {{ $department->name }}</h3>
		<a href="{{route('department.index')}}" class="btn btn-success">Back</a>
		<hr>

		<table class= "table table-hover">
		<thead>
			<th>Role</th>
			<th>Salary</th>
		</thead>
		
		<tbody>
			@if($department->roles->count() > 0)
				@foreach($department->roles as $role)
					<tr>
						<td>
							<a href="{{ route('role.show', ['slug'=>$role->slug])}}">{{ $role->name }}</a>
						</td>
						<td>{{ $role->salary }}</td>
					</tr>
				@endforeach
			@else
				<tr> 
					<th colspan="5" class="text-center">No Roles assigned in this department yet</th>
				</tr>
			@endif
		
		</tbody>
	
	</table>
</div>		
@endsection